[package]
name = "templet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_reflect = "0.10.1"
byteorder = "1.4.3"
thiserror = "1.0.40"
