[package]
name = "templet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fnv = "1.0.7"
nom = "7.1.0"
nom_locate = "4.0.0"
valuable = { version = "0.1.0", features = ["derive"] }
